# Tier 1
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT1
  equipment:
    pocket1: SpaceCash500
    gloves: ClothingHandsMercenaryGlovesCombat
    shoes: ClothingShoesBootsMercenary
    mask: ClothingMaskGasMercenary
    belt: ClothingBeltMercenaryWebbing
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - Truncheon
    - MakeshiftShield

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT1
  equipment:
    gloves: ClothingHandsMercenaryGlovesCombat
    back: ClothingBackpackDuffelMecranaryTier1Pistol
    belt: ClothingBeltWebbingMecranaryTier1Pistol
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - WeaponPistolMk58Expedition

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT1
  equipment:
    gloves: ClothingHandsMercenaryGlovesCombat
    back: ClothingBackpackDuffelMecranaryTier1Novalite
    belt: ClothingBeltWebbingMecranaryTier1Novalite
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - WeaponRifleNovaliteC1Expedition

# Tier 2
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT2
  equipment:
    pocket2: SpaceCash1000
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    mask: ClothingMaskGasSwat
    belt: ClothingBeltMilitaryWebbing
    outerClothing: ClothingOuterVestWebMercenaryBlack
    head: ClothingHeadHelmetMercenaryBlack
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckBlueMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - Machete
    - RiotShield

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT2
  equipment:
    back: ClothingBackpackDuffelMecranaryTier2Revolver
    belt: ClothingBeltWebbingMecranaryTier2Revolver
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterVestWebMercenaryBlack
    head: ClothingHeadHelmetMercenaryBlack
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckBlueMercenary
    neck: ClothingNeckIFFGreen
 inhand:
    - WeaponRevolverArgentiExpedition
    - WeaponRevolverArgentiExpedition

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT2
  equipment:
    back: ClothingBackpackDuffelMecranaryTier2Shotgun
    belt: ClothingBeltWebbingMecranaryTier2Shotgun
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterVestWebMercenaryBlack
    head: ClothingHeadHelmetMercenaryBlack
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckBlueMercenary
    neck: ClothingNeckIFFGreen
 inhand:
    - WeaponShotgunDoubleBarreledExpedition

# Tier 3
- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3
  equipment:
    back: ClothingBackpackDuffelMecranaryTier3Medic
    belt: ClothingBeltMecranaryTier3Medic
    gloves: ClothingHandsGlovesNitrile
    shoes: ClothingShoesBootsCombat
    mask: ClothingMaskBreathMedicalSecurity
    outerClothing: ClothingOuterVestWebMercenaryBlack
    head: ClothingHeadHatParamedicsoft
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckBlueMercenaryMedic
    neck: ClothingNeckIFFGreen
 inhand:
    - WeaponLaserGunExpedition
    - SawElectric

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3Alt
  equipment:
    back: ClothingBackpackDuffelMecranaryTier3Assault
    belt: ClothingBeltMecranaryTier3Assault
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterVestWebMercenaryBlack
    head: ClothingHeadHelmetMercenaryBlack
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckBlueMercenary
    neck: ClothingNeckIFFGreen
 inhand:
    - WeaponRifleGestio

# Tier 4
- type: startingGear
  id: MobHumanoidMercenaryGearTier4Captain
  equipment:
    back: ClothingBackpackDuffelMecranaryTier4Captain
    gloves: ClothingHandsMercenaryGlovesCombat
    shoes: ClothingShoesBootsMercenary
    belt: ClothingBeltMercenaryWebbing
    mask: Cigar
    outerClothing: ClothingOuterHardsuitMercenary
    head: ClothingHeadHatBeretMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenaryCaptain
    neck: ClothingNeckIFFGreen
 inhand:
    - WeaponSniperRepeaterExpedition
