# Tier 1
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT1
  equipment:
    pocket1: SpaceCash500
    gloves: ClothingHandsMercenaryGlovesCombat
    shoes: ClothingShoesBootsMercenary
    mask: ClothingMaskGasMercenary
    belt: ClothingBeltMercenaryWebbing
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - Truncheon
    - MakeshiftShield

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT1
  equipment:
    gloves: ClothingHandsGlovesColorMercPistol
    back: ClothingBackpackDuffelMecranaryTier1Pistol
    belt: ClothingBeltWebbingMecranaryTier1Pistol
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT1
  equipment:
    gloves: ClothingHandsGlovesColorMercNovalite
    back: ClothingBackpackDuffelMecranaryTier1Novalite
    belt: ClothingBeltWebbingMecranaryTier1Novalite
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

# Tier 2
- type: startingGear
  id: MobHumanoidMercenaryGearMeleeT2
  equipment:
    pocket2: SpaceCash1000
    gloves: ClothingHandsMercenaryGlovesCombat
    shoes: ClothingShoesBootsMercenary
    mask: ClothingMaskGasMercenary
    belt: ClothingBeltMercenaryWebbing
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    neck: ClothingNeckIFFGreen
  inhand:
    - Machete
    - RiotShield

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT2
  equipment:
    gloves: ClothingHandsGlovesColorMercRevolvers
    back: ClothingBackpackDuffelMecranaryTier2Revolver
    belt: ClothingBeltWebbingMecranaryTier2Revolver
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

- type: startingGear
  id: MobHumanoidMercenaryGearRangedAltT2
  equipment:
    gloves: ClothingHandsGlovesColorMercShotgun
    back: ClothingBackpackDuffelMecranaryTier2Shotgun
    belt: ClothingBeltWebbingMecranaryTier2Shotgun
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

# Tier 3
- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3
  equipment:
    gloves: ClothingHandsGlovesColorMercLaserNSaw
    back: ClothingBackpackDuffelMecranaryTier3Medic
    belt: ClothingBeltMecranaryTier3Medic
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

- type: startingGear
  id: MobHumanoidMercenaryGearRangedT3Alt
  equipment:
    gloves: ClothingHandsGlovesColorMercGestio
    back: ClothingBackpackDuffelMecranaryTier3Assault
    belt: ClothingBeltMecranaryTier3Assault
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen

# Tier 4
- type: startingGear
  id: MobHumanoidMercenaryGearTier4Captain
  equipment:
    gloves: ClothingHandsGlovesColorMercRepeater
    back: ClothingBackpackDuffelMecranaryTier4Captain
    shoes: ClothingShoesBootsMercenary
    outerClothing: ClothingOuterVestWebMercenary
    head: ClothingHeadHelmetMercenary
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenary
    mask: ClothingMaskGasMercenary
    neck: ClothingNeckIFFGreen
