# Tier 1
- type: startingGear
  id: PunkGangerGearMeleeT1
  equipment:
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkLootA
  inhand:
    - BaseBallBat

- type: startingGear
  id: PunkGangerGearPistol
  equipment:
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    gloves: ClothingHandsGlovesColorBlackPistol
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkLootB

# Tier 2
- type: startingGear
  id: PunkGangerGearMeleeT2
  equipment:
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    pocket2: ClothingBackpackPunkLootA
  inhand:
    - FireAxe

- type: startingGear
  id: PunkGangerGearShotgun
  equipment:
    neck: PunkHandsGlovesShotgun
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    pocket2: ClothingBackpackPunkLootC

# Tier 3
- type: startingGear
  id: PunkGangerGearMeleeT3
  equipment:
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    pocket2: ClothingBackpackPunkLootA
  inhand:
    - Sledgehammer

- type: startingGear
  id: PunkGangerGearSmg
  equipment:
    neck: PunkHandsGlovesSmg
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    pocket2: ClothingBackpackPunkLootD

# Tier 4
- type: startingGear
  id: PunkGangerGearLaser
  equipment:
    neck: PunkHandsGlovesLaserGun
    eyes: ClothingEyesPunkInfoShades
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    back: PortableRecharger
    pocket2: ClothingBackpackPunkLootBoss
