# Tier 1
- type: startingGear
  id: PunkGangerGearMeleeT1
  equipment:
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    back: ClothingBackpackPunkLootA
  inhand:
    - BaseBallBat

- type: startingGear
  id: PunkGangerGearPistol
  equipment:
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    back: ClothingBackpackPunkLootB
  inhand:
    - WeaponPistolMk58Expedition

# Tier 2
- type: startingGear
  id: PunkGangerGearMeleeT2
  equipment:
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    back: ClothingBackpackPunkLootA
  inhand:
    - FireAxe

- type: startingGear
  id: PunkGangerGearShotgun
  equipment:
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkCroptop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterCoatBomberRandomized
    back: ClothingBackpackPunkLootC
  inhand:
    - WeaponShotgunKammererExpedition

# Tier 3
- type: startingGear
  id: PunkGangerGearMeleeT3
  equipment:
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    back: ClothingBackpackPunkLootA
  inhand:
    - Sledgehammer

- type: startingGear
  id: PunkGangerGearSmg
  equipment:
    eyes: ClothingEyesPunkGoggles
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorPunkRandomized
    back: ClothingBackpackPunkLootD
  inhand:
    - WeaponSubMachineGunDrozdExpedition

# Tier 4
- type: startingGear
  id: PunkGangerGearLaser
  equipment:
    eyes: ClothingEyesPunkInfoShades
    mask: ClothingMaskPunkHalf
    jumpsuit: ClothingUniformRandomPunkTanktop
    belt: ClothingBeltPunkRandomized
    shoes: ClothingShoesBootsPunkRandomized
    outerClothing: ClothingOuterArmorElitePunkRandomized
    back: PortableRecharger
    pocket2: ClothingBackpackPunkLootBoss
  inhand:
    - WeaponLaserCarbineExpedition
